spring:
  application:    name: Config-Server
#  security:#    user:#      name: ${CONFIG-ADMIN-NAME}
#      password: ${CONFIG-PASSWORD}
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}          search-paths:
          - User-Microservice*